CONFIG += no_fixpath
QT = core gui widgets
CONFIG += no_fixpath
QT = core sql network gui widgets serialport websockets
CONFIG += no_fixpath
QT = core sql network gui widgets serialport websockets
CONFIG += no_fixpath
QT = core sql network gui widgets serialport websockets
CONFIG += no_fixpath
QT = core sql network gui widgets serialport websockets
